#navbar section

brand-logo: /img/brand-logo.png
menu:
  - name: Facilities
    link:
  
  - name: News
    link:

  - name: Contact
    link:

  - name: Reservation
    link:


#cover section
cover-bg: /img/cover-bg.jpg
cover-title: RV resort meets urban farm
cover-description: Austonia is a first of a kind project that brings the best of Austin to those passing through or staying for a while.
cover-button-text: Book your stay
cover-button-link: 