#navbar section

brand-logo: /img/brand-logo.png
menu:
  - name: Facilities
    link:
  
  - name: News
    link:

  - name: Contact
    link:

  - name: Reservation
    link:


#cover section
cover-bg: /img/cover-bg.jpg
cover-title: RV resort meets urban farm
cover-description: Austonia is a first of a kind project that brings the best of Austin to those passing through or staying for a while.
cover-button-text: Book your stay
cover-button-link: 

#about section
about-title: The story
about-description: Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
about-bg: /img/about-cover.jpg 